# Generated by Django 2.0.2 on 2018-02-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_priority',
            new_name='task_prio',
        ),
    ]
