# Generated by Django 2.0.2 on 2018-02-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20180213_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_prio',
            new_name='task_priority',
        ),
    ]
