# Generated by Django 2.0.2 on 2018-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20180213_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_info',
            field=models.CharField(default='task', max_length=200),
            preserve_default=False,
        ),
    ]
