# Generated by Django 2.0.2 on 2018-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_task_task_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_done',
            field=models.CharField(default='todo', max_length=4),
            preserve_default=False,
        ),
    ]
